baseURL = "/"
theme = "creastel-pages"
languageCode = "en-us"
languageLang = "en"
title = "Creastel Docs"
defaultContentLanguage = "en"
disableKinds = ["RSS"]

[params]
  disableHLJS = true
  disableScrollBarStyle = true
  description = "Creastel Docs"
  author = "Creastel SAS"
  displayFullLangName = true
  [assets]
    favicon = "static/images/favicon.ico"
    favicon16x16 = "static/images/favicon.ico"
    favicon32x32 = "static/images/favicon.ico"
    apple_touch_icon = "static/images/logo512.png"
    safari_pinned_tab = "static/images/logo512.png"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.taxonomies]
      product = "products"
  [languages.fr]
    languageName = "Français"
    weight = 1
    [languages.fr.taxonomies]
      product = "products"